### ISSUE TITLE
Unable to fetch listing Error 403

### ISSUE THREAD

**Issue by reinisb** [martinsbalodis/xbmc-lattelecom.tv#17]
Hei!

Tikko veicu jaunu setup uz jaunākā macOS. Izskatās, ka logins ir success un kanālu EPG arī ielādē. Taču, kad nospiežu uz kanāla, lai to atskaņotu, tad izmet šo Unable to fetch listing Error 403. Es novērtētu, ja varētu pasviest kādu ideju kā šo novērst, paldies!

`2019-06-30 10:50:15.263 T:123145448992768  NOTICE: [Lattelecom Live TV v0.4.8] Login success! Token: tokenu izdzesu no shejienes
2019-06-30 10:50:15.548 T:123145452748800  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
2019-06-30 10:50:21.220 T:123145438720000  NOTICE: [Lattelecom Live TV v0.4.8] Initialised
2019-06-30 10:50:21.220 T:123145438720000  NOTICE: [Lattelecom Live TV v0.4.8] got URL: plugin://lattelecomtv/; 1; ?play=true&data_url=101; resume:false
2019-06-30 10:50:21.220 T:123145438720000  NOTICE: [Lattelecom Live TV v0.4.8] url play channel: plugin://lattelecomtv/
2019-06-30 10:50:21.220 T:123145438720000  NOTICE: [Lattelecom Live TV v0.4.8] Getting URL for channel: 101
2019-06-30 10:50:21.225 T:123145438720000  NOTICE: [Lattelecom Live TV v0.4.8] Lattelecom login token seems quite fresh.
2019-06-30 10:50:23.333 T:123145438720000  NOTICE: [Lattelecom Live TV v0.4.8] ERROR: play_channel (49) - HTTP Error 403: Forbidden
2019-06-30 10:50:23.333 T:123145438720000   ERROR: Traceback (most recent call last):
2019-06-30 10:50:23.334 T:123145438720000   ERROR:   File "/Users/agnete/Library/Application Support/Kodi/addons/lattelecomtv/lib/channels.py", line 49, in play_channel
2019-06-30 10:50:23.334 T:123145438720000   ERROR:     rtmp_url = api.get_stream_url(data_url)
2019-06-30 10:50:23.334 T:123145438720000   ERROR:   File "/Users/agnete/Library/Application Support/Kodi/addons/lattelecomtv/lib/api.py", line 132, in get_stream_url
2019-06-30 10:50:23.334 T:123145438720000   ERROR:     response = opener.open(url)
2019-06-30 10:50:23.335 T:123145438720000   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/urllib2.py", line 435, in open
2019-06-30 10:50:23.335 T:123145438720000   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/urllib2.py", line 548, in http_response
2019-06-30 10:50:23.335 T:123145438720000   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/urllib2.py", line 473, in error
2019-06-30 10:50:23.335 T:123145438720000   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/urllib2.py", line 407, in _call_chain
2019-06-30 10:50:23.335 T:123145438720000   ERROR:   File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.13_x86_64-target-release/lib/python2.7/urllib2.py", line 556, in http_error_default
2019-06-30 10:50:23.335 T:123145438720000   ERROR: HTTPError: HTTP Error 403: Forbidden`

![Screenshot 2019-06-30 at 10 50 34](https://user-images.githubusercontent.com/6346595/60393955-9f497f00-9b25-11e9-965e-7af2b499edb3.png)

**Comment by Janhouse** [comment]
"Works on my machine" 😃 
Tu no Latvijas IP adreses mēģini? Vai mobilajā aplikācijā strādā?
Nesen tikai mainījām API versiju tiem izsaukumiem kas iet uz pleilistes novilkšanu lai varētu skatīties visus kanālus, arī no citiem provaideriem (vismaz Latvijā). Man šķiet, ka šis plugins tagad strādā kā "mazie ekrāni" Lattelecom aprakstā.
Esmu mēģinājis no Lattelecom, Bite, Latnet, Baltcom un vēl pāris ISP un nav bijušas problēmas.

**Comment by reinisb** [comment]
Tikko pamēģināju uz cita macbook - tā pati problēma. Lattelecom IP adrese. Savukārt uz raspberry pi viss strādā. Izrietoši secinu, ka šī ir macos problēma. Tiesa, kādreiz uz Kodi+macOS viss strādāja perfekti.

Pēc log izskatās, ka vaina ir saistīta ar urllib2.py - vai ir idejas, kas konkrēti varētu būt pie vainas?
<img width="1428" alt="Screenshot 2019-07-18 at 10 14 49" src="https://user-images.githubusercontent.com/6346595/61437187-2334a100-a945-11e9-9467-f3d1bc3d9eec.png">

**Comment by Janhouse** [comment]
Man uz macOS strādā

**Comment by reinisb** [comment]
> Man uz macOS strādā

Hmm...vai tev uz macOS ir jaunākā addona 0.4.7 versija? Jautāju, jo es tikko uninstallēju 0.4.7 un tā vietā ieinstalēju priekšpēdējo pieejamo [versiju 0.4.0](https://github.com/martinsbalodis/xbmc-lattelecom.tv/releases) un viss strādā. Izrietoši, šķiet, ka kāda no versijām pēc 0.4.0 salauza atbalstu ar maniem macOS (mēģināju uz diviem macbookiem, abiem jaunākā macOS Mojave 10.14.6).

**Comment by Janhouse** [comment]
Varēja būt saistīts ar API izmaiņām kas atrisinātas keisā #18
Pagaidām veru ciet. Ja vēl ir aktuāli, iekomentē.

**Comment by reinisb** [comment]
@Janhouse paldies! Tikko pamēģināju uz macOS Catalina 10.15.1 (19B88), kodi 18.5, addona versija 0.5.0,  lattelecom IP, bet tāpat nestrādā. Tas pats arī uz raspberry pi OSMC jaunākās versijas. Pievienoju Log no macOS.

[kodi.log](https://github.com/martinsbalodis/xbmc-lattelecom.tv/files/3934248/kodi.log)

![Screenshot 2019-12-07 at 00 20 21](https://user-images.githubusercontent.com/6346595/70360656-ca2fc000-1887-11ea-87eb-02d60ab1c96b.png)

**Comment by reinisb** [comment]
False alarm, viss aizgāja - nebiju pareizi autorizējies. Paldies - apstiprinu, ka viss strādā!
