### ISSUE TITLE
Vakar pārstāja darboties

### ISSUE THREAD

**Issue by reinisb** [martinsbalodis/xbmc-lattelecom.tv#18]
Sveiciens! Vakar pārstāja darboties uz visām Kodi iekārtām - gan raspberry, gan macos (uz macos pēdējo pusgadu vairs nedarbojās, jo kaut pēc 0.4.0 versijas mainījās). Vai jums darbojas? cc @Janhouse 

```
2019-11-26 21:46:31.631 T:1393554144  NOTICE: [Lattelecom Live TV v0.4.7] Initialised
2019-11-26 21:46:31.631 T:1393554144  NOTICE: [Lattelecom Live TV v0.4.7] got URL: plugin://lattelecomtv/; 3; ?play=true&data_url=101; resume:false
2019-11-26 21:46:31.632 T:1393554144  NOTICE: [Lattelecom Live TV v0.4.7] url play channel: plugin://lattelecomtv/
2019-11-26 21:46:31.632 T:1393554144  NOTICE: [Lattelecom Live TV v0.4.7] Getting URL for channel: 101
2019-11-26 21:46:31.645 T:1393554144  NOTICE: [Lattelecom Live TV v0.4.7] Refreshing Lattelecom login token
2019-11-26 21:46:31.653 T:1393554144  NOTICE: [Lattelecom Live TV v0.4.7] User: izdzests; Logged in: 1; Token: izdzests
2019-11-26 21:46:34.177 T:1393554144  NOTICE: [Lattelecom Live TV v0.4.7] ERROR: play_channel (50) - HTTP Error 404: Not Found
2019-11-26 21:46:34.177 T:1393554144   ERROR: Traceback (most recent call last):
2019-11-26 21:46:34.177 T:1393554144   ERROR:   File "/home/osmc/.kodi/addons/lattelecomtv/lib/channels.py", line 50, in play_channel
2019-11-26 21:46:34.179 T:1393554144   ERROR:     rtmp_url = api.get_stream_url(data_url)
2019-11-26 21:46:34.179 T:1393554144   ERROR:   File "/home/osmc/.kodi/addons/lattelecomtv/lib/api.py", line 125, in get_stream_url
2019-11-26 21:46:34.181 T:1393554144   ERROR:     config.login_check()
2019-11-26 21:46:34.181 T:1393554144   ERROR:   File "/home/osmc/.kodi/addons/lattelecomtv/lib/config.py", line 115, in login_check
2019-11-26 21:46:34.182 T:1393554144   ERROR:     api.login(force=True)
2019-11-26 21:46:34.182 T:1393554144   ERROR:   File "/home/osmc/.kodi/addons/lattelecomtv/lib/api.py", line 43, in login
2019-11-26 21:46:34.182 T:1393554144   ERROR:     response = opener.open(API_ENDPOINT + '/api/v1.4/post/user/login', urllib.urlencode(values))
2019-11-26 21:46:34.182 T:1393554144   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 435, in open
2019-11-26 21:46:34.184 T:1393554144   ERROR:     response = meth(req, response)
2019-11-26 21:46:34.184 T:1393554144   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
2019-11-26 21:46:34.184 T:1393554144   ERROR:     'http', request, response, code, msg, hdrs)
2019-11-26 21:46:34.185 T:1393554144   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 473, in error
2019-11-26 21:46:34.185 T:1393554144   ERROR:     return self._call_chain(*args)
2019-11-26 21:46:34.185 T:1393554144   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
2019-11-26 21:46:34.185 T:1393554144   ERROR:     result = func(*args)
2019-11-26 21:46:34.185 T:1393554144   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
2019-11-26 21:46:34.185 T:1393554144   ERROR:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
2019-11-26 21:46:34.185 T:1393554144   ERROR: HTTPError: HTTP Error 404: Not Found

```

**Comment by Janhouse** [comment]
Uzliku tikko uz macOS Kodi updeitu, nodzēsu cache, tagad redzu to pašu problēmu.
Interesanti, ka uz TV kastes man viss joprojām strādā (Archlinux nodrošina jaunāko Kodi un mans update repo pēdējo plugina versiju), bet tur neko neesmu dzēsis.
Kādā brīvā brīdī safixošu.

**Comment by reinisb** [comment]
Ok, paldies - ar nepacietību gaidu, kad izdosies safixot!

**Comment by reinisb** [comment]
Gribēju uzsvērt, ka manā gadījumā nestrādā gan uz macOS, gan uz raspbrry pi OSMC (log augstāk).

**Comment by Janhouse** [comment]
Versija 0.5.0 ir pieejama repozitorijā. Notestēju uz pāris iekārtām, šķiet, ka strādā.
